FROM alpine:latest AS final
WORKDIR /

COPY ./dist/linux/cezzis-cocktails /cezzis-cocktails

# Make sure the binary is executable
RUN chmod +x /cezzis-cocktails

# add non-root runtime user
RUN addgroup -S app && adduser -S -G app app
USER app

EXPOSE 8080

CMD ["/cezzis-cocktails"]