apiVersion: dapr.io/v1alpha1
kind: Resiliency

metadata:
  name: cocktails-mcp-dapr-resiliency

spec:
  policies:
    retries:
      defaultRetry:
        policy: constant
        duration: 5s
        maxRetries: 3

    circuitBreakers:
      defaultCircuitBreaker:
        maxRequests: 1
        interval: 10s
        timeout: 30s
        trip: consecutiveFailures >= 3
