version: "2"
linters:
  enable:
    - govet
    - staticcheck
    - errcheck
    - unused
    - gocyclo
    - revive
  settings:
    gocyclo:
      min-complexity: 15
    revive:
      confidence: 0.8
      severity: warning
      rules:
        - name: var-naming
        - name: package-comments
        - name: blank-imports
        - name: indent-error-flow
        - name: if-return
        - name: import-shadowing
        - name: range-val-address
        - name: error-naming
        - name: exported
        - name: time-naming
  exclusions:
    generated: lax
    rules:
      - linters:
          - errcheck
          - staticcheck
        path: _test\.go
    paths:
      - third_party$
      - builtin$
      - examples$
issues:
  max-issues-per-linter: 0
  max-same-issues: 0
formatters:
  enable:
    - gofmt
    - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
        - cezzis.com/cezzis-mcp-server
