FROM alpine:latest AS final
WORKDIR /

COPY ./dist/linux/cezzis-cocktails /cezzis-cocktails

# Make sure the binary is executable
RUN chmod +x /cezzis-cocktails

EXPOSE 8080
EXPOSE 7999

CMD ["/cezzis-cocktails"]