apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cezzis-com-cocktails-mcp-shared-secrets
  namespace: cezzis
  labels:
    app.kubernetes.io/part-of: cezzis
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: shared-secret-store
    kind: SecretStore
  target:
    name: cezzis-com-cocktails-mcp-shared-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        OTLP_HEADERS: "Authorization=Bearer {{ .otelApiKey }}"
        POSTGRES_PASSWORD: "{{ .postgresAppPassword }}"
  data:
    - secretKey: otelApiKey
      remoteRef:
        key: otel-collector-api-key-onprem
    - secretKey: postgresAppPassword
      remoteRef:
        key: postgres-app-password-onprem
---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cezzis-com-cocktails-mcp-secrets
  namespace: cezzis
  labels:
    app.kubernetes.io/part-of: cezzis
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: cezzis-prd-secret-store
    kind: SecretStore
  target:
    name: cezzis-com-cocktails-mcp-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        DAPR_API_TOKEN: "{{ .daprApiToken }}"
        APP_API_TOKEN: "{{ .appApiToken }}"
  data:
    - secretKey: daprApiToken
      remoteRef:
        key: shared-daprio-dapr-api-token
    - secretKey: appApiToken
      remoteRef:
        key: shared-daprio-app-api-token
