apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cezzis-com-cocktails-mcp-shared-secrets
  namespace: cezzis
  labels:
    app.kubernetes.io/part-of: cezzis
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "100"
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: shared-prm-secret-store
    kind: SecretStore
  target:
    name: cezzis-com-cocktails-mcp-shared-secrets
    creationPolicy: Owner
    template:
      engineVersion: v2
      data:
        OTLP_HEADERS: "Authorization=Bearer {{ .otelApiKey }}"
        POSTGRES_PASSWORD: "{{ .postgresAppPassword }}"
  data:
    - secretKey: otelApiKey
      remoteRef:
        key: otel-collector-api-key
    - secretKey: postgresAppPassword
      remoteRef:
        key: postgres-app-password
