// Package aisearch provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package aisearch

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"

	"github.com/oapi-codegen/runtime"
)

const (
	Auth0Scopes = "auth0.Scopes"
)

// Defines values for CocktailDataIncludeModel.
const (
	DescriptiveTitle CocktailDataIncludeModel = "descriptiveTitle"
	MainImages       CocktailDataIncludeModel = "mainImages"
	SearchTiles      CocktailDataIncludeModel = "searchTiles"
)

// Defines values for GlasswareTypeModel.
const (
	GlasswareTypeModelCocktailGlass     GlasswareTypeModel = "cocktailGlass"
	GlasswareTypeModelCollins           GlasswareTypeModel = "collins"
	GlasswareTypeModelCopperMug         GlasswareTypeModel = "copperMug"
	GlasswareTypeModelCoupe             GlasswareTypeModel = "coupe"
	GlasswareTypeModelDoubleRocks       GlasswareTypeModel = "doubleRocks"
	GlasswareTypeModelFizz              GlasswareTypeModel = "fizz"
	GlasswareTypeModelFlute             GlasswareTypeModel = "flute"
	GlasswareTypeModelHighball          GlasswareTypeModel = "highball"
	GlasswareTypeModelHollowedPineapple GlasswareTypeModel = "hollowedPineapple"
	GlasswareTypeModelHurricane         GlasswareTypeModel = "hurricane"
	GlasswareTypeModelJulepTin          GlasswareTypeModel = "julepTin"
	GlasswareTypeModelLowball           GlasswareTypeModel = "lowball"
	GlasswareTypeModelNone              GlasswareTypeModel = "none"
	GlasswareTypeModelPintGlass         GlasswareTypeModel = "pintGlass"
	GlasswareTypeModelRocks             GlasswareTypeModel = "rocks"
	GlasswareTypeModelScorpionBowl      GlasswareTypeModel = "scorpionBowl"
	GlasswareTypeModelShotGlass         GlasswareTypeModel = "shotGlass"
	GlasswareTypeModelSnifter           GlasswareTypeModel = "snifter"
	GlasswareTypeModelTikiMug           GlasswareTypeModel = "tikiMug"
	GlasswareTypeModelWineGlass         GlasswareTypeModel = "wineGlass"
)

// Defines values for IngredientApplicationTypeModel.
const (
	Additional  IngredientApplicationTypeModel = "additional"
	Base        IngredientApplicationTypeModel = "base"
	Garnishment IngredientApplicationTypeModel = "garnishment"
	Muddle      IngredientApplicationTypeModel = "muddle"
)

// Defines values for IngredientRequirementTypeModel.
const (
	IngredientRequirementTypeModelNone     IngredientRequirementTypeModel = "none"
	IngredientRequirementTypeModelOptional IngredientRequirementTypeModel = "optional"
	IngredientRequirementTypeModelRequired IngredientRequirementTypeModel = "required"
)

// Defines values for IngredientTypeModel.
const (
	Beer      IngredientTypeModel = "beer"
	Bitters   IngredientTypeModel = "bitters"
	Champagne IngredientTypeModel = "champagne"
	Dilution  IngredientTypeModel = "dilution"
	Flowers   IngredientTypeModel = "flowers"
	Fruit     IngredientTypeModel = "fruit"
	Herb      IngredientTypeModel = "herb"
	Juice     IngredientTypeModel = "juice"
	Liqueur   IngredientTypeModel = "liqueur"
	Protein   IngredientTypeModel = "protein"
	Sauce     IngredientTypeModel = "sauce"
	Spirit    IngredientTypeModel = "spirit"
	Syrup     IngredientTypeModel = "syrup"
	Vegetable IngredientTypeModel = "vegetable"
	Wine      IngredientTypeModel = "wine"
)

// Defines values for PreparationTypeModel.
const (
	PreparationTypeModelChilled         PreparationTypeModel = "chilled"
	PreparationTypeModelFreshPressed    PreparationTypeModel = "freshPressed"
	PreparationTypeModelFreshlyGrated   PreparationTypeModel = "freshlyGrated"
	PreparationTypeModelFreshlySqueezed PreparationTypeModel = "freshlySqueezed"
	PreparationTypeModelNone            PreparationTypeModel = "none"
	PreparationTypeModelPeeledAndJuiced PreparationTypeModel = "peeledAndJuiced"
	PreparationTypeModelQuartered       PreparationTypeModel = "quartered"
)

// Defines values for UofMTypeModel.
const (
	UofMTypeModelBarspoon   UofMTypeModel = "barspoon"
	UofMTypeModelCups       UofMTypeModel = "cups"
	UofMTypeModelDashes     UofMTypeModel = "dashes"
	UofMTypeModelDiscretion UofMTypeModel = "discretion"
	UofMTypeModelItem       UofMTypeModel = "item"
	UofMTypeModelNone       UofMTypeModel = "none"
	UofMTypeModelOunces     UofMTypeModel = "ounces"
	UofMTypeModelSplash     UofMTypeModel = "splash"
	UofMTypeModelTablespoon UofMTypeModel = "tablespoon"
	UofMTypeModelTeaspoon   UofMTypeModel = "teaspoon"
	UofMTypeModelToTaste    UofMTypeModel = "toTaste"
	UofMTypeModelTopoff     UofMTypeModel = "topoff"
)

// CocktailDataIncludeModel defines model for CocktailDataIncludeModel.
type CocktailDataIncludeModel string

// CocktailDescriptionChunk defines model for CocktailDescriptionChunk.
type CocktailDescriptionChunk struct {
	// Category Category of the description chunk
	Category string `json:"category"`

	// Content Textual content of the description chunk
	Content string `json:"content"`
}

// CocktailEmbeddingRq Request model for embedding cocktail description chunks into the vector database.
type CocktailEmbeddingRq struct {
	CocktailModel CocktailModelInput `json:"cocktail_model"`

	// ContentChunks List of text chunks to be embedded
	ContentChunks []CocktailDescriptionChunk `json:"content_chunks"`
}

// CocktailModelInput defines model for CocktailModel-Input.
type CocktailModelInput struct {
	// DescriptiveTitle Descriptive title of the cocktail
	DescriptiveTitle string `json:"descriptiveTitle"`

	// Glassware List of glassware types used for the cocktail
	Glassware []GlasswareTypeModel `json:"glassware"`

	// Id Unique identifier for the cocktail
	Id string `json:"id"`

	// Ingredients List of ingredients in the cocktail
	Ingredients []IngredientModel `json:"ingredients"`

	// IsIba Indicates if the cocktail is an IBA official cocktail
	IsIba bool `json:"isIba"`

	// PrepTimeMinutes Preparation time in minutes
	PrepTimeMinutes int `json:"prepTimeMinutes"`

	// Rating Rating of the cocktail
	Rating float32 `json:"rating"`

	// SearchTiles Search tiles associated with the cocktail
	SearchTiles      []string                  `json:"searchTiles"`
	SearchStatistics *CocktailSearchStatistics `json:"search_statistics,omitempty"`

	// Serves Number of servings
	Serves int `json:"serves"`

	// Title Title of the cocktail
	Title string `json:"title"`
}

// CocktailModelOutput defines model for CocktailModel-Output.
type CocktailModelOutput struct {
	// DescriptiveTitle Descriptive title of the cocktail
	DescriptiveTitle string `json:"descriptiveTitle"`

	// Glassware List of glassware types used for the cocktail
	Glassware []GlasswareTypeModel `json:"glassware"`

	// Id Unique identifier for the cocktail
	Id string `json:"id"`

	// Ingredients List of ingredients in the cocktail
	Ingredients []IngredientModel `json:"ingredients"`

	// IsIba Indicates if the cocktail is an IBA official cocktail
	IsIba bool `json:"isIba"`

	// PrepTimeMinutes Preparation time in minutes
	PrepTimeMinutes int `json:"prepTimeMinutes"`

	// Rating Rating of the cocktail
	Rating float32 `json:"rating"`

	// SearchTiles Search tiles associated with the cocktail
	SearchTiles      []string                  `json:"searchTiles"`
	SearchStatistics *CocktailSearchStatistics `json:"search_statistics,omitempty"`

	// Serves Number of servings
	Serves int `json:"serves"`

	// Title Title of the cocktail
	Title string `json:"title"`
}

// CocktailSearchStatistics defines model for CocktailSearchStatistics.
type CocktailSearchStatistics struct {
	// HitResults List of hit results with their scores
	HitResults *[]CocktailVectorSearchResult `json:"hit_results,omitempty"`

	// TotalScore Total score of the search result
	TotalScore float32 `json:"total_score"`
}

// CocktailVectorSearchResult defines model for CocktailVectorSearchResult.
type CocktailVectorSearchResult struct {
	// Score Score of the search result
	Score float32 `json:"score"`
}

// CocktailsSearchRs defines model for CocktailsSearchRs.
type CocktailsSearchRs struct {
	// Items List of cocktails returned from the search
	Items []CocktailModelOutput `json:"items"`
}

// GlasswareTypeModel defines model for GlasswareTypeModel.
type GlasswareTypeModel string

// HealthCheckRs defines model for HealthCheckRs.
type HealthCheckRs struct {
	Details *map[string]interface{} `json:"details"`
	Output  *string                 `json:"output"`
	Status  string                  `json:"status"`
	Version *string                 `json:"version"`
}

// IngredientApplicationTypeModel defines model for IngredientApplicationTypeModel.
type IngredientApplicationTypeModel string

// IngredientModel defines model for IngredientModel.
type IngredientModel struct {
	// Applications List of ingredient applications
	Applications []IngredientApplicationTypeModel `json:"applications"`

	// Display Display string for the ingredient
	Display string `json:"display"`

	// Name Name of the ingredient
	Name        string                         `json:"name"`
	Preparation PreparationTypeModel           `json:"preparation"`
	Requirement IngredientRequirementTypeModel `json:"requirement"`

	// Suggestions Suggestions for the ingredient
	Suggestions string `json:"suggestions"`

	// Types List of ingredient types
	Types []IngredientTypeModel `json:"types"`

	// Units Quantity of the ingredient
	Units float32 `json:"units"`

	// UoM The unit of measurment types for cocktail ingredients.
	UoM UofMTypeModel `json:"uoM"`
}

// IngredientRequirementTypeModel defines model for IngredientRequirementTypeModel.
type IngredientRequirementTypeModel string

// IngredientTypeModel defines model for IngredientTypeModel.
type IngredientTypeModel string

// PreparationTypeModel defines model for PreparationTypeModel.
type PreparationTypeModel string

// ProblemDetails RFC 7807 compliant problem details model.
//
// This model provides a standard way to carry machine-readable details
// of errors in HTTP response bodies.
type ProblemDetails struct {
	// Detail A human-readable explanation specific to this occurrence of the problem
	Detail *string `json:"detail"`

	// Errors A dictionary of validation errors, where keys are field names and values are lists of error messages
	Errors *map[string][]string `json:"errors"`

	// Extensions Additional extension members for problem-specific information
	Extensions *map[string]interface{} `json:"extensions"`

	// Instance A URI reference that identifies the specific occurrence of the problem
	Instance *string `json:"instance"`

	// Status The HTTP status code generated by the origin server
	Status int `json:"status"`

	// Title A short, human-readable summary of the problem type
	Title string `json:"title"`

	// Type A URI reference that identifies the problem type
	Type *string `json:"type,omitempty"`
}

// UofMTypeModel The unit of measurment types for cocktail ingredients.
type UofMTypeModel string

// PutV1CocktailsEmbeddingsParams defines parameters for PutV1CocktailsEmbeddings.
type PutV1CocktailsEmbeddingsParams struct {
	// XKey The API gateway subscription key
	XKey string `json:"X-Key"`
}

// GetV1CocktailsSearchParams defines parameters for GetV1CocktailsSearch.
type GetV1CocktailsSearchParams struct {
	// Freetext The free text search term to match against
	Freetext *string `form:"freetext,omitempty" json:"freetext,omitempty"`

	// Skip The number of cocktail recipes to skip from the paged response
	Skip *int `form:"skip,omitempty" json:"skip,omitempty"`

	// Take The number of cocktail recipes to take for pagination
	Take *int `form:"take,omitempty" json:"take,omitempty"`

	// M A list of cocktails that can be included in the list
	M *[]string `form:"m,omitempty" json:"m,omitempty"`

	// MEx Whether or not the supplied matches must be exclusively returned
	MEx *bool `form:"m_ex,omitempty" json:"m_ex,omitempty"`

	// Inc The list of extension objects to include for each cocktail recipe
	Inc *[]CocktailDataIncludeModel `form:"inc,omitempty" json:"inc,omitempty"`

	// Fi An optional list of filters to use when quering the cocktail recipes
	Fi *[]string `form:"fi,omitempty" json:"fi,omitempty"`

	// XKey The API gateway subscription key
	XKey string `json:"X-Key"`
}

// GetV1CocktailsTypeaheadParams defines parameters for GetV1CocktailsTypeahead.
type GetV1CocktailsTypeaheadParams struct {
	// Freetext The free text search term to match against
	Freetext *string `form:"freetext,omitempty" json:"freetext,omitempty"`

	// Skip The number of cocktail recipes to skip from the paged response
	Skip *int `form:"skip,omitempty" json:"skip,omitempty"`

	// Take The number of cocktail recipes to take for pagination
	Take *int `form:"take,omitempty" json:"take,omitempty"`

	// Fi An optional list of filters to use when quering the cocktail recipes
	Fi *[]string `form:"fi,omitempty" json:"fi,omitempty"`

	// XKey The API gateway subscription key
	XKey string `json:"X-Key"`
}

// PutV1CocktailsEmbeddingsJSONRequestBody defines body for PutV1CocktailsEmbeddings for application/json ContentType.
type PutV1CocktailsEmbeddingsJSONRequestBody = CocktailEmbeddingRq

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PutV1CocktailsEmbeddingsWithBody request with any body
	PutV1CocktailsEmbeddingsWithBody(ctx context.Context, params *PutV1CocktailsEmbeddingsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PutV1CocktailsEmbeddings(ctx context.Context, params *PutV1CocktailsEmbeddingsParams, body PutV1CocktailsEmbeddingsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetV1CocktailsSearch request
	GetV1CocktailsSearch(ctx context.Context, params *GetV1CocktailsSearchParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetV1CocktailsTypeahead request
	GetV1CocktailsTypeahead(ctx context.Context, params *GetV1CocktailsTypeaheadParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// HealthCheckV1HealthGet request
	HealthCheckV1HealthGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PutV1CocktailsEmbeddingsWithBody(ctx context.Context, params *PutV1CocktailsEmbeddingsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutV1CocktailsEmbeddingsRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PutV1CocktailsEmbeddings(ctx context.Context, params *PutV1CocktailsEmbeddingsParams, body PutV1CocktailsEmbeddingsJSONRequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPutV1CocktailsEmbeddingsRequest(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetV1CocktailsSearch(ctx context.Context, params *GetV1CocktailsSearchParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV1CocktailsSearchRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetV1CocktailsTypeahead(ctx context.Context, params *GetV1CocktailsTypeaheadParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetV1CocktailsTypeaheadRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) HealthCheckV1HealthGet(ctx context.Context, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewHealthCheckV1HealthGetRequest(c.Server)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPutV1CocktailsEmbeddingsRequest calls the generic PutV1CocktailsEmbeddings builder with application/json body
func NewPutV1CocktailsEmbeddingsRequest(server string, params *PutV1CocktailsEmbeddingsParams, body PutV1CocktailsEmbeddingsJSONRequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPutV1CocktailsEmbeddingsRequestWithBody(server, params, "application/json", bodyReader)
}

// NewPutV1CocktailsEmbeddingsRequestWithBody generates requests for PutV1CocktailsEmbeddings with any type of body
func NewPutV1CocktailsEmbeddingsRequestWithBody(server string, params *PutV1CocktailsEmbeddingsParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/cocktails/embeddings")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "X-Key", runtime.ParamLocationHeader, params.XKey)
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Key", headerParam0)

	}

	return req, nil
}

// NewGetV1CocktailsSearchRequest generates requests for GetV1CocktailsSearch
func NewGetV1CocktailsSearchRequest(server string, params *GetV1CocktailsSearchParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/cocktails/search")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Freetext != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "freetext", runtime.ParamLocationQuery, *params.Freetext); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Skip != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "skip", runtime.ParamLocationQuery, *params.Skip); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Take != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "take", runtime.ParamLocationQuery, *params.Take); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.M != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "m", runtime.ParamLocationQuery, *params.M); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.MEx != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "m_ex", runtime.ParamLocationQuery, *params.MEx); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Inc != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "inc", runtime.ParamLocationQuery, *params.Inc); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Fi != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "fi", runtime.ParamLocationQuery, *params.Fi); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "X-Key", runtime.ParamLocationHeader, params.XKey)
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Key", headerParam0)

	}

	return req, nil
}

// NewGetV1CocktailsTypeaheadRequest generates requests for GetV1CocktailsTypeahead
func NewGetV1CocktailsTypeaheadRequest(server string, params *GetV1CocktailsTypeaheadParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/cocktails/typeahead")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Freetext != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "freetext", runtime.ParamLocationQuery, *params.Freetext); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Skip != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "skip", runtime.ParamLocationQuery, *params.Skip); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Take != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "take", runtime.ParamLocationQuery, *params.Take); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Fi != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "fi", runtime.ParamLocationQuery, *params.Fi); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		var headerParam0 string

		headerParam0, err = runtime.StyleParamWithLocation("simple", false, "X-Key", runtime.ParamLocationHeader, params.XKey)
		if err != nil {
			return nil, err
		}

		req.Header.Set("X-Key", headerParam0)

	}

	return req, nil
}

// NewHealthCheckV1HealthGetRequest generates requests for HealthCheckV1HealthGet
func NewHealthCheckV1HealthGetRequest(server string) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/v1/health")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PutV1CocktailsEmbeddingsWithBodyWithResponse request with any body
	PutV1CocktailsEmbeddingsWithBodyWithResponse(ctx context.Context, params *PutV1CocktailsEmbeddingsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutV1CocktailsEmbeddingsResponse, error)

	PutV1CocktailsEmbeddingsWithResponse(ctx context.Context, params *PutV1CocktailsEmbeddingsParams, body PutV1CocktailsEmbeddingsJSONRequestBody, reqEditors ...RequestEditorFn) (*PutV1CocktailsEmbeddingsResponse, error)

	// GetV1CocktailsSearchWithResponse request
	GetV1CocktailsSearchWithResponse(ctx context.Context, params *GetV1CocktailsSearchParams, reqEditors ...RequestEditorFn) (*GetV1CocktailsSearchResponse, error)

	// GetV1CocktailsTypeaheadWithResponse request
	GetV1CocktailsTypeaheadWithResponse(ctx context.Context, params *GetV1CocktailsTypeaheadParams, reqEditors ...RequestEditorFn) (*GetV1CocktailsTypeaheadResponse, error)

	// HealthCheckV1HealthGetWithResponse request
	HealthCheckV1HealthGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthCheckV1HealthGetResponse, error)
}

type PutV1CocktailsEmbeddingsResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSONDefault                   *ProblemDetails
	ApplicationproblemJSONDefault *ProblemDetails
}

// Status returns HTTPResponse.Status
func (r PutV1CocktailsEmbeddingsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PutV1CocktailsEmbeddingsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetV1CocktailsSearchResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *CocktailsSearchRs
	JSONDefault                   *ProblemDetails
	ApplicationproblemJSONDefault *ProblemDetails
}

// Status returns HTTPResponse.Status
func (r GetV1CocktailsSearchResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV1CocktailsSearchResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetV1CocktailsTypeaheadResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *CocktailsSearchRs
	JSONDefault                   *ProblemDetails
	ApplicationproblemJSONDefault *ProblemDetails
}

// Status returns HTTPResponse.Status
func (r GetV1CocktailsTypeaheadResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetV1CocktailsTypeaheadResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type HealthCheckV1HealthGetResponse struct {
	Body                          []byte
	HTTPResponse                  *http.Response
	JSON200                       *HealthCheckRs
	JSONDefault                   *ProblemDetails
	ApplicationproblemJSONDefault *ProblemDetails
}

// Status returns HTTPResponse.Status
func (r HealthCheckV1HealthGetResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r HealthCheckV1HealthGetResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PutV1CocktailsEmbeddingsWithBodyWithResponse request with arbitrary body returning *PutV1CocktailsEmbeddingsResponse
func (c *ClientWithResponses) PutV1CocktailsEmbeddingsWithBodyWithResponse(ctx context.Context, params *PutV1CocktailsEmbeddingsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PutV1CocktailsEmbeddingsResponse, error) {
	rsp, err := c.PutV1CocktailsEmbeddingsWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutV1CocktailsEmbeddingsResponse(rsp)
}

func (c *ClientWithResponses) PutV1CocktailsEmbeddingsWithResponse(ctx context.Context, params *PutV1CocktailsEmbeddingsParams, body PutV1CocktailsEmbeddingsJSONRequestBody, reqEditors ...RequestEditorFn) (*PutV1CocktailsEmbeddingsResponse, error) {
	rsp, err := c.PutV1CocktailsEmbeddings(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePutV1CocktailsEmbeddingsResponse(rsp)
}

// GetV1CocktailsSearchWithResponse request returning *GetV1CocktailsSearchResponse
func (c *ClientWithResponses) GetV1CocktailsSearchWithResponse(ctx context.Context, params *GetV1CocktailsSearchParams, reqEditors ...RequestEditorFn) (*GetV1CocktailsSearchResponse, error) {
	rsp, err := c.GetV1CocktailsSearch(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV1CocktailsSearchResponse(rsp)
}

// GetV1CocktailsTypeaheadWithResponse request returning *GetV1CocktailsTypeaheadResponse
func (c *ClientWithResponses) GetV1CocktailsTypeaheadWithResponse(ctx context.Context, params *GetV1CocktailsTypeaheadParams, reqEditors ...RequestEditorFn) (*GetV1CocktailsTypeaheadResponse, error) {
	rsp, err := c.GetV1CocktailsTypeahead(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetV1CocktailsTypeaheadResponse(rsp)
}

// HealthCheckV1HealthGetWithResponse request returning *HealthCheckV1HealthGetResponse
func (c *ClientWithResponses) HealthCheckV1HealthGetWithResponse(ctx context.Context, reqEditors ...RequestEditorFn) (*HealthCheckV1HealthGetResponse, error) {
	rsp, err := c.HealthCheckV1HealthGet(ctx, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseHealthCheckV1HealthGetResponse(rsp)
}

// ParsePutV1CocktailsEmbeddingsResponse parses an HTTP response from a PutV1CocktailsEmbeddingsWithResponse call
func ParsePutV1CocktailsEmbeddingsResponse(rsp *http.Response) (*PutV1CocktailsEmbeddingsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PutV1CocktailsEmbeddingsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.Header.Get("Content-Type") == "application/json" && true:
		var dest ProblemDetails
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	case rsp.Header.Get("Content-Type") == "application/problem+json" && true:
		var dest ProblemDetails
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	}

	return response, nil
}

// ParseGetV1CocktailsSearchResponse parses an HTTP response from a GetV1CocktailsSearchWithResponse call
func ParseGetV1CocktailsSearchResponse(rsp *http.Response) (*GetV1CocktailsSearchResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV1CocktailsSearchResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.Header.Get("Content-Type") == "application/json" && true:
		var dest ProblemDetails
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	case rsp.Header.Get("Content-Type") == "application/problem+json" && true:
		var dest ProblemDetails
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CocktailsSearchRs
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseGetV1CocktailsTypeaheadResponse parses an HTTP response from a GetV1CocktailsTypeaheadWithResponse call
func ParseGetV1CocktailsTypeaheadResponse(rsp *http.Response) (*GetV1CocktailsTypeaheadResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetV1CocktailsTypeaheadResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.Header.Get("Content-Type") == "application/json" && true:
		var dest ProblemDetails
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	case rsp.Header.Get("Content-Type") == "application/problem+json" && true:
		var dest ProblemDetails
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CocktailsSearchRs
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}

// ParseHealthCheckV1HealthGetResponse parses an HTTP response from a HealthCheckV1HealthGetWithResponse call
func ParseHealthCheckV1HealthGetResponse(rsp *http.Response) (*HealthCheckV1HealthGetResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &HealthCheckV1HealthGetResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case rsp.Header.Get("Content-Type") == "application/json" && true:
		var dest ProblemDetails
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSONDefault = &dest

	case rsp.Header.Get("Content-Type") == "application/problem+json" && true:
		var dest ProblemDetails
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationproblemJSONDefault = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest HealthCheckRs
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.JSON200 = &dest

	}

	return response, nil
}
