apiVersion: dapr.io/v1alpha1
kind: Configuration
metadata:
  name: cocktails-mcp-dapr-config
  namespace: cezzis
  labels:
    app.kubernetes.io/part-of: cezzis
    app.kubernetes.io/managed-by: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "200"
spec:
  tracing:
    samplingRate: "1"
    otel:
      endpointAddress: "otel-collector.openobserve-platform.svc.cluster.local:4317"
      isSecure: false
      protocol: grpc
  logging:
    apiLogging:
      enabled: true
      obfuscateURLs: false
  metrics:
    enabled: true
    rules: []
    http:
      increasedCardinality: true
    latencyDistributionBuckets: [1, 2, 5, 10, 25, 50, 100, 250, 500, 1000, 2500, 5000, 10000]
