// Package cocktailsapi provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package cocktailsapi

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"net/url"
	"strings"
	"time"

	"github.com/oapi-codegen/runtime"
)

const (
	Oauth2Scopes = "oauth2.Scopes"
)

// Defines values for GetCocktailParamsMeasurementSystem.
const (
	Imperial GetCocktailParamsMeasurementSystem = "imperial"
	Metric   GetCocktailParamsMeasurementSystem = "metric"
)

// CocktailCollectionListModel defines model for CocktailCollectionListModel.
type CocktailCollectionListModel struct {
	// Description The cocktail collection description
	Description string `json:"description"`

	// Holiday The holiday rule for a holiday collection
	Holiday NullableOfCollectionHolidayTypeModel `json:"holiday"`

	// Id The cocktail collection identifier
	Id string `json:"id"`

	// ImageUrl The collection image URL
	ImageUrl string `json:"imageUrl"`

	// Intro The collection intro text for the landing page
	Intro string `json:"intro"`

	// Order The display order of the collection
	Order int32 `json:"order"`

	// RelatedCollectionIds The related collection identifiers
	RelatedCollectionIds []string `json:"relatedCollectionIds"`

	// Season The season rule for a seasonal collection
	Season NullableOfCollectionSeasonTypeModel `json:"season"`

	// ShortTitle The short collection title for compact displays
	ShortTitle string `json:"shortTitle"`

	// Title The cocktail collection title
	Title string `json:"title"`

	// Visibility The collection visibility type
	Visibility CollectionVisibilityTypeModel `json:"visibility"`
}

// CocktailCollectionModel The cocktail collection model
type CocktailCollectionModel struct {
	// CocktailIds The cocktail identifiers in the collection
	CocktailIds []string `json:"cocktailIds"`

	// Description The cocktail collection description
	Description string `json:"description"`

	// Holiday The holiday rule for a holiday collection
	Holiday NullableOfCollectionHolidayTypeModel `json:"holiday"`

	// Id The cocktail collection identifier
	Id string `json:"id"`

	// ImageUrl The collection image URL
	ImageUrl string `json:"imageUrl"`

	// Intro The collection intro text for the landing page
	Intro string `json:"intro"`

	// Order The display order of the collection
	Order int32 `json:"order"`

	// RelatedCollectionIds The related collection identifiers
	RelatedCollectionIds []string `json:"relatedCollectionIds"`

	// Season The season rule for a seasonal collection
	Season NullableOfCollectionSeasonTypeModel `json:"season"`

	// ShortTitle The short collection title for compact displays
	ShortTitle string `json:"shortTitle"`

	// Title The cocktail collection title
	Title string `json:"title"`

	// Visibility The collection visibility type
	Visibility CollectionVisibilityTypeModel `json:"visibility"`
}

// CocktailCollectionRs defines model for CocktailCollectionRs.
type CocktailCollectionRs struct {
	// Item The cocktail collection model
	Item CocktailCollectionModel `json:"item"`
}

// CocktailCollectionsRs defines model for CocktailCollectionsRs.
type CocktailCollectionsRs struct {
	// Items The visible cocktail collections
	Items []CocktailCollectionListModel `json:"items"`
}

// CocktailImageModel defines model for CocktailImageModel.
type CocktailImageModel struct {
	// Height The height of the image
	Height int32 `json:"height"`

	// Uri The uri of the image
	Uri string `json:"uri"`

	// Width The width of the image
	Width int32 `json:"width"`
}

// CocktailImageModel2 defines model for CocktailImageModel2.
type CocktailImageModel2 struct {
	// Height The height of the image
	Height int32 `json:"height"`

	// Uri The uri of the image
	Uri string `json:"uri"`

	// Width The width of the image
	Width int32 `json:"width"`
}

// CocktailIngredientFiltersRs defines model for CocktailIngredientFiltersRs.
type CocktailIngredientFiltersRs struct {
	// AromaticsTeaAndCoffee The cocktail ingredient filters for searching against aromatics, tea, and coffee
	AromaticsTeaAndCoffee []interface{} `json:"aromaticsTeaAndCoffee"`

	// Bitters The cocktail ingredient filters for searching against bitters
	Bitters []interface{} `json:"bitters"`

	// DairyAndEggs The cocktail ingredient filters for searching against dairy and eggs
	DairyAndEggs []interface{} `json:"dairyAndEggs"`

	// Eras The cocktail ingredient filters for searching against eras when cocktails were established
	Eras []interface{} `json:"eras"`

	// FruitsAndCitrus The cocktail ingredient filters for searching against fruits and citrus
	FruitsAndCitrus []interface{} `json:"fruitsAndCitrus"`

	// JuicesAndPurees The cocktail ingredient filters for searching against juices and purees
	JuicesAndPurees []interface{} `json:"juicesAndPurees"`

	// LiqueursAperitifsAndAmari The cocktail ingredient filters for searching against liqueurs, aperitifs, and amari
	LiqueursAperitifsAndAmari []interface{} `json:"liqueursAperitifsAndAmari"`

	// MixersSodaAndWater The cocktail ingredient filters for searching against mixers, soda, and water
	MixersSodaAndWater []interface{} `json:"mixersSodaAndWater"`

	// SavoryBrinyAndHeat The cocktail ingredient filters for searching against savory, briny, and heat ingredients
	SavoryBrinyAndHeat []interface{} `json:"savoryBrinyAndHeat"`

	// Spirits The cocktail ingredient filters for searching against spirits
	Spirits []IngredientFilterModel `json:"spirits"`

	// SweetenersAndSyrups The cocktail ingredient filters for searching against sweeteners and syrups
	SweetenersAndSyrups []interface{} `json:"sweetenersAndSyrups"`

	// VegetablesAndSavoryProduce The cocktail ingredient filters for searching against vegetables and savory produce
	VegetablesAndSavoryProduce []interface{} `json:"vegetablesAndSavoryProduce"`

	// WineBeerAndSake The cocktail ingredient filters for searching against wine, beer, and sake ingredients
	WineBeerAndSake []interface{} `json:"wineBeerAndSake"`
}

// CocktailKeywordsModel The keywords associated with the cocktail recipe
type CocktailKeywordsModel struct {
	// KeywordsBaseSpirit Base spirit keywords
	KeywordsBaseSpirit []string `json:"keywordsBaseSpirit"`

	// KeywordsCocktailFamily Cocktail family keywords
	KeywordsCocktailFamily []string `json:"keywordsCocktailFamily"`

	// KeywordsFlavorProfile Flavor profile keywords
	KeywordsFlavorProfile []string `json:"keywordsFlavorProfile"`

	// KeywordsMood Mood keywords
	KeywordsMood []string `json:"keywordsMood"`

	// KeywordsOccasion Occasion keywords
	KeywordsOccasion []string `json:"keywordsOccasion"`

	// KeywordsSearchTerms Search terms keywords
	KeywordsSearchTerms []string `json:"keywordsSearchTerms"`

	// KeywordsSeason Season keywords
	KeywordsSeason []string `json:"keywordsSeason"`

	// KeywordsSpiritSubtype Spirits subtype keywords
	KeywordsSpiritSubtype []string `json:"keywordsSpiritSubtype"`

	// KeywordsStrength Strength keyword
	KeywordsStrength string `json:"keywordsStrength"`

	// KeywordsTechnique Technique keywords
	KeywordsTechnique []string `json:"keywordsTechnique"`

	// KeywordsTemperature Temperature keyword
	KeywordsTemperature string `json:"keywordsTemperature"`
}

// CocktailModel The cocktail recipe model
type CocktailModel struct {
	// Collections A list of collections that this cocktail recipe belongs to
	Collections []string `json:"collections"`

	// Content The complete descriptive cocktail recipe including ingredients, directions and historical information in markdown format
	Content string `json:"content"`

	// Description A brief editorial description for the cocktail recipe
	Description string `json:"description"`

	// DescriptiveTitle A more descriptive title for the cocktail recipe, generally used as an editorial title
	DescriptiveTitle string `json:"descriptiveTitle"`

	// Glassware The recommended glassware to use when serving the cocktail
	Glassware []GlasswareTypeModel `json:"glassware"`

	// Id The cocktail recipe unique identifier
	Id string `json:"id"`

	// Ingredients The list of ingredients that make up the cocktail recipe
	Ingredients []IngredientModel `json:"ingredients"`

	// Instructions The list of instructions to make the cocktail recipe
	Instructions []InstructionStepModel `json:"instructions"`

	// IsIba Whether or not the cocktail represented by this recipe is recognized by the International Bartenders Association
	IsIba bool `json:"isIba"`

	// Keywords The keywords associated with the cocktail recipe
	Keywords CocktailKeywordsModel `json:"keywords"`

	// MainImages A list of primary images for the cocktail recipe
	MainImages []CocktailImageModel `json:"mainImages"`

	// ModifiedOn The date this cocktail recipe was last modified on Cezzis.Com
	ModifiedOn time.Time `json:"modifiedOn"`

	// PrepTimeMinutes The average number of minutes to build the cocktail using this recipe
	PrepTimeMinutes int32 `json:"prepTimeMinutes"`

	// PublishedOn The date this cocktail recipe was published on Cezzis.Com
	PublishedOn time.Time `json:"publishedOn"`

	// Rating A ratings for this cocktail
	Rating CocktailRatingModel `json:"rating"`

	// SearchTiles A list of secondary, smaller sized images for the cocktail recipe
	SearchTiles []CocktailImageModel2 `json:"searchTiles"`

	// SearchableTitles A list of titles that are queried against when issuing cocktail recipe search queries
	SearchableTitles []string `json:"searchableTitles"`

	// Serves The number of people the cocktail recipe serves
	Serves int32 `json:"serves"`

	// Tags A list of taxonomy tags defining the cocktail recipe
	Tags []string `json:"tags"`

	// Title The name of the cocktail recipe
	Title string `json:"title"`
}

// CocktailRatingModel A ratings for this cocktail
type CocktailRatingModel struct {
	// FiveStars The number of five star ratings
	FiveStars int32 `json:"fiveStars"`

	// FourStars The number of four star ratings
	FourStars int32 `json:"fourStars"`

	// OneStars The number of one star ratings
	OneStars int32 `json:"oneStars"`

	// Rating The actual overal rating
	Rating float64 `json:"rating"`

	// RatingCount The total number of ratings given
	RatingCount int32 `json:"ratingCount"`

	// ThreeStars The number of three star ratings
	ThreeStars int32 `json:"threeStars"`

	// TotalStars The total number of stars given
	TotalStars int32 `json:"totalStars"`

	// TwoStars The number of two star ratings
	TwoStars int32 `json:"twoStars"`
}

// CocktailRs defines model for CocktailRs.
type CocktailRs struct {
	// Item The cocktail recipe model
	Item CocktailModel `json:"item"`
}

// CollectionVisibilityTypeModel The collection visibility type
type CollectionVisibilityTypeModel = interface{}

// DocumentFormat The format that the document content is in
type DocumentFormat = interface{}

// GlasswareTypeModel defines model for GlasswareTypeModel.
type GlasswareTypeModel = interface{}

// IngredientApplicationModel defines model for IngredientApplicationModel.
type IngredientApplicationModel = interface{}

// IngredientFilterModel defines model for IngredientFilterModel.
type IngredientFilterModel struct {
	// Id The filter identifier
	Id string `json:"id"`

	// Name The display name of the filter
	Name string `json:"name"`
}

// IngredientModel defines model for IngredientModel.
type IngredientModel struct {
	// Applications The ingredient applications that this ingredient is in relation to the cocktail recipe
	Applications []IngredientApplicationModel `json:"applications"`

	// Display Gets the complete display value for the ingredient including units and measurments
	Display string `json:"display"`

	// Name The name of the ingredient
	Name string `json:"name"`

	// Preparation Any preparation that should be made with this ingredient
	Preparation PreparationTypeModel `json:"preparation"`

	// Requirement Whether or not this ingredient is required ('Required' or 'Optional')
	Requirement IngredientRequirementTypeModel `json:"requirement"`

	// Suggestions Suggestion when using this ingredient
	Suggestions string `json:"suggestions"`

	// TaxonomyFilterType The ingredient filter group used for cocktail search filters
	TaxonomyFilterType TaxonomyFilterTypeModel `json:"taxonomyFilterType"`

	// Types The ordered ingredient taxonomy from broad to specific
	Types []string `json:"types"`

	// Units The number of units to use in relation to the UoM (unit of measure) in the cocktail recipe
	Units float32 `json:"units"`

	// UoM The unit of measure when using this ingredient in a cocktail recipe
	UoM UofMTypeModel `json:"uoM"`
}

// IngredientRequirementTypeModel Whether or not this ingredient is required ('Required' or 'Optional')
type IngredientRequirementTypeModel = interface{}

// IngredientRs defines model for IngredientRs.
type IngredientRs struct {
	// Item The ingredient model
	Item InventoryIngredientModel `json:"item"`
}

// IngredientVariationModel defines model for IngredientVariationModel.
type IngredientVariationModel struct {
	// Applications The applications this ingredient variation can be used as
	Applications []IngredientApplicationModel `json:"applications"`

	// Id The ingredient variation identifier
	Id string `json:"id"`

	// Name The ingredient variation name
	Name string `json:"name"`
}

// IngredientsRs defines model for IngredientsRs.
type IngredientsRs struct {
	// Items The paged ingredient list
	Items []InventoryIngredientModel2 `json:"items"`

	// Skip The number of items skipped from the start of the ingredient collection
	Skip int32 `json:"skip"`

	// Take The number of items requested from the ingredient collection
	Take int32 `json:"take"`
}

// InstructionStepModel defines model for InstructionStepModel.
type InstructionStepModel struct {
	// Display The displayable value for the instruction step
	Display string `json:"display"`

	// Order The order of the instruction step in which it should be performed
	Order int32 `json:"order"`
}

// InventoryIngredientModel The ingredient model
type InventoryIngredientModel struct {
	// Applications The ingredient applications
	Applications []IngredientApplicationModel `json:"applications"`

	// Id The ingredient identifier
	Id string `json:"id"`

	// Name The ingredient name
	Name string `json:"name"`

	// ParentId The parent ingredient identifier
	ParentId string `json:"parentId"`

	// PublishedOn The date and time this ingredient was published
	PublishedOn time.Time `json:"publishedOn"`

	// ShelfDisplay The ingredient shelf display name
	ShelfDisplay string `json:"shelfDisplay"`

	// TaxonomyFilterType The ingredient filter group used for cocktail search filters
	TaxonomyFilterType TaxonomyFilterTypeModel `json:"taxonomyFilterType"`

	// Types The ordered ingredient taxonomy from broad to specific
	Types []string `json:"types"`

	// Variations The ingredient variations
	Variations []IngredientVariationModel `json:"variations"`
}

// InventoryIngredientModel2 defines model for InventoryIngredientModel2.
type InventoryIngredientModel2 struct {
	// Applications The ingredient applications
	Applications []IngredientApplicationModel `json:"applications"`

	// Id The ingredient identifier
	Id string `json:"id"`

	// Name The ingredient name
	Name string `json:"name"`

	// ParentId The parent ingredient identifier
	ParentId string `json:"parentId"`

	// PublishedOn The date and time this ingredient was published
	PublishedOn time.Time `json:"publishedOn"`

	// ShelfDisplay The ingredient shelf display name
	ShelfDisplay string `json:"shelfDisplay"`

	// TaxonomyFilterType The ingredient filter group used for cocktail search filters
	TaxonomyFilterType TaxonomyFilterTypeModel `json:"taxonomyFilterType"`

	// Types The ordered ingredient taxonomy from broad to specific
	Types []string `json:"types"`

	// Variations The ingredient variations
	Variations []IngredientVariationModel `json:"variations"`
}

// LegalDocumentRs defines model for LegalDocumentRs.
type LegalDocumentRs struct {
	// Document The document content
	Document string `json:"document"`

	// Format The format that the document content is in
	Format DocumentFormat `json:"format"`
}

// NullableOfCollectionHolidayTypeModel The holiday rule for a holiday collection
type NullableOfCollectionHolidayTypeModel = interface{}

// NullableOfCollectionSeasonTypeModel The season rule for a seasonal collection
type NullableOfCollectionSeasonTypeModel = interface{}

// PreparationTypeModel Any preparation that should be made with this ingredient
type PreparationTypeModel = interface{}

// ProblemDetails defines model for ProblemDetails.
type ProblemDetails struct {
	Detail   *string `json:"detail"`
	Instance *string `json:"instance"`
	Status   *int32  `json:"status"`
	Title    *string `json:"title"`
	Type     *string `json:"type"`
}

// PublishCocktailsRq defines model for PublishCocktailsRq.
type PublishCocktailsRq struct {
	// CocktailIds A list of cocktail IDs to publish
	CocktailIds []string `json:"cocktailIds"`
}

// PublishIngredientsRq defines model for PublishIngredientsRq.
type PublishIngredientsRq struct {
	// IngredientIds A list of ingredient IDs to publish. Empty means publish all ingredients
	IngredientIds []string `json:"ingredientIds"`
}

// TaxonomyFilterTypeModel The ingredient filter group used for cocktail search filters
type TaxonomyFilterTypeModel = interface{}

// UofMTypeModel The unit of measure when using this ingredient in a cocktail recipe
type UofMTypeModel = interface{}

// PublishCocktailsParams defines parameters for PublishCocktails.
type PublishCocktailsParams struct {
	// XKey Subscription key
	XKey *string `json:"X-Key,omitempty"`
}

// PublishIngredientsParams defines parameters for PublishIngredients.
type PublishIngredientsParams struct {
	// XKey Subscription key
	XKey *string `json:"X-Key,omitempty"`
}

// GetCocktailCollectionsParams defines parameters for GetCocktailCollections.
type GetCocktailCollectionsParams struct {
	// XKey Subscription key
	XKey *string `json:"X-Key,omitempty"`
}

// GetCocktailCollectionParams defines parameters for GetCocktailCollection.
type GetCocktailCollectionParams struct {
	// XKey Subscription key
	XKey *string `json:"X-Key,omitempty"`
}

// GetIngredientsParams defines parameters for GetIngredients.
type GetIngredientsParams struct {
	// Skip The number of ingredients to skip
	Skip *int32 `form:"skip,omitempty" json:"skip,omitempty"`

	// Take The number of ingredients to return. Maximum value is 50
	Take *int32 `form:"take,omitempty" json:"take,omitempty"`

	// Fi Filters ingredients by taxonomy node. Use repeatable fi query values such as fi=spirits&fi=whiskey
	Fi *[]string `form:"fi,omitempty" json:"fi,omitempty"`

	// XKey Subscription key
	XKey *string `json:"X-Key,omitempty"`
}

// GetCocktailIngredientFiltersParams defines parameters for GetCocktailIngredientFilters.
type GetCocktailIngredientFiltersParams struct {
	// XKey Subscription key
	XKey *string `json:"X-Key,omitempty"`
}

// GetIngredientParams defines parameters for GetIngredient.
type GetIngredientParams struct {
	// XKey Subscription key
	XKey *string `json:"X-Key,omitempty"`
}

// GetCocktailParams defines parameters for GetCocktail.
type GetCocktailParams struct {
	// ResolveIngredients Whether to resolve the ingredients display values in the content
	ResolveIngredients *bool `form:"resolveIngredients,omitempty" json:"resolveIngredients,omitempty"`

	// MeasurementSystem The measurement system for ingredient display values (imperial or metric).
	MeasurementSystem *GetCocktailParamsMeasurementSystem `form:"measurementSystem,omitempty" json:"measurementSystem,omitempty"`

	// XKey Subscription key
	XKey *string `json:"X-Key,omitempty"`
}

// GetCocktailParamsMeasurementSystem defines parameters for GetCocktail.
type GetCocktailParamsMeasurementSystem string

// GetPrivacyPolicyParams defines parameters for GetPrivacyPolicy.
type GetPrivacyPolicyParams struct {
	// XKey Subscription key
	XKey *string `json:"X-Key,omitempty"`
}

// GetTermsOfServiceParams defines parameters for GetTermsOfService.
type GetTermsOfServiceParams struct {
	// XKey Subscription key
	XKey *string `json:"X-Key,omitempty"`
}

// PublishCocktailsApplicationJSONXAPIVersion10RequestBody defines body for PublishCocktails for application/json; x-api-version=1.0 ContentType.
type PublishCocktailsApplicationJSONXAPIVersion10RequestBody = PublishCocktailsRq

// PublishIngredientsApplicationJSONXAPIVersion10RequestBody defines body for PublishIngredients for application/json; x-api-version=1.0 ContentType.
type PublishIngredientsApplicationJSONXAPIVersion10RequestBody = PublishIngredientsRq

// RequestEditorFn  is the function signature for the RequestEditor callback function
type RequestEditorFn func(ctx context.Context, req *http.Request) error

// Doer performs HTTP requests.
//
// The standard http.Client implements this interface.
type HttpRequestDoer interface {
	Do(req *http.Request) (*http.Response, error)
}

// Client which conforms to the OpenAPI3 specification for this service.
type Client struct {
	// The endpoint of the server conforming to this interface, with scheme,
	// https://api.deepmap.com for example. This can contain a path relative
	// to the server, such as https://api.deepmap.com/dev-test, and all the
	// paths in the swagger spec will be appended to the server.
	Server string

	// Doer for performing requests, typically a *http.Client with any
	// customized settings, such as certificate chains.
	Client HttpRequestDoer

	// A list of callbacks for modifying requests which are generated before sending over
	// the network.
	RequestEditors []RequestEditorFn
}

// ClientOption allows setting custom parameters during construction
type ClientOption func(*Client) error

// Creates a new Client, with reasonable defaults
func NewClient(server string, opts ...ClientOption) (*Client, error) {
	// create a client with sane default values
	client := Client{
		Server: server,
	}
	// mutate client and add all optional params
	for _, o := range opts {
		if err := o(&client); err != nil {
			return nil, err
		}
	}
	// ensure the server URL always has a trailing slash
	if !strings.HasSuffix(client.Server, "/") {
		client.Server += "/"
	}
	// create httpClient, if not already present
	if client.Client == nil {
		client.Client = &http.Client{}
	}
	return &client, nil
}

// WithHTTPClient allows overriding the default Doer, which is
// automatically created using http.Client. This is useful for tests.
func WithHTTPClient(doer HttpRequestDoer) ClientOption {
	return func(c *Client) error {
		c.Client = doer
		return nil
	}
}

// WithRequestEditorFn allows setting up a callback function, which will be
// called right before sending the request. This can be used to mutate the request.
func WithRequestEditorFn(fn RequestEditorFn) ClientOption {
	return func(c *Client) error {
		c.RequestEditors = append(c.RequestEditors, fn)
		return nil
	}
}

// The interface specification for the client above.
type ClientInterface interface {
	// PublishCocktailsWithBody request with any body
	PublishCocktailsWithBody(ctx context.Context, params *PublishCocktailsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PublishCocktailsWithApplicationJSONXAPIVersion10Body(ctx context.Context, params *PublishCocktailsParams, body PublishCocktailsApplicationJSONXAPIVersion10RequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// PublishIngredientsWithBody request with any body
	PublishIngredientsWithBody(ctx context.Context, params *PublishIngredientsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error)

	PublishIngredientsWithApplicationJSONXAPIVersion10Body(ctx context.Context, params *PublishIngredientsParams, body PublishIngredientsApplicationJSONXAPIVersion10RequestBody, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetCocktailCollections request
	GetCocktailCollections(ctx context.Context, params *GetCocktailCollectionsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetCocktailCollection request
	GetCocktailCollection(ctx context.Context, id string, params *GetCocktailCollectionParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetIngredients request
	GetIngredients(ctx context.Context, params *GetIngredientsParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetCocktailIngredientFilters request
	GetCocktailIngredientFilters(ctx context.Context, params *GetCocktailIngredientFiltersParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetIngredient request
	GetIngredient(ctx context.Context, id string, params *GetIngredientParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetCocktail request
	GetCocktail(ctx context.Context, id string, params *GetCocktailParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetPrivacyPolicy request
	GetPrivacyPolicy(ctx context.Context, params *GetPrivacyPolicyParams, reqEditors ...RequestEditorFn) (*http.Response, error)

	// GetTermsOfService request
	GetTermsOfService(ctx context.Context, params *GetTermsOfServiceParams, reqEditors ...RequestEditorFn) (*http.Response, error)
}

func (c *Client) PublishCocktailsWithBody(ctx context.Context, params *PublishCocktailsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPublishCocktailsRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PublishCocktailsWithApplicationJSONXAPIVersion10Body(ctx context.Context, params *PublishCocktailsParams, body PublishCocktailsApplicationJSONXAPIVersion10RequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPublishCocktailsRequestWithApplicationJSONXAPIVersion10Body(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PublishIngredientsWithBody(ctx context.Context, params *PublishIngredientsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPublishIngredientsRequestWithBody(c.Server, params, contentType, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) PublishIngredientsWithApplicationJSONXAPIVersion10Body(ctx context.Context, params *PublishIngredientsParams, body PublishIngredientsApplicationJSONXAPIVersion10RequestBody, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewPublishIngredientsRequestWithApplicationJSONXAPIVersion10Body(c.Server, params, body)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetCocktailCollections(ctx context.Context, params *GetCocktailCollectionsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCocktailCollectionsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetCocktailCollection(ctx context.Context, id string, params *GetCocktailCollectionParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCocktailCollectionRequest(c.Server, id, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetIngredients(ctx context.Context, params *GetIngredientsParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetIngredientsRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetCocktailIngredientFilters(ctx context.Context, params *GetCocktailIngredientFiltersParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCocktailIngredientFiltersRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetIngredient(ctx context.Context, id string, params *GetIngredientParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetIngredientRequest(c.Server, id, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetCocktail(ctx context.Context, id string, params *GetCocktailParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetCocktailRequest(c.Server, id, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetPrivacyPolicy(ctx context.Context, params *GetPrivacyPolicyParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetPrivacyPolicyRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

func (c *Client) GetTermsOfService(ctx context.Context, params *GetTermsOfServiceParams, reqEditors ...RequestEditorFn) (*http.Response, error) {
	req, err := NewGetTermsOfServiceRequest(c.Server, params)
	if err != nil {
		return nil, err
	}
	req = req.WithContext(ctx)
	if err := c.applyEditors(ctx, req, reqEditors); err != nil {
		return nil, err
	}
	return c.Client.Do(req)
}

// NewPublishCocktailsRequestWithApplicationJSONXAPIVersion10Body calls the generic PublishCocktails builder with application/json; x-api-version=1.0 body
func NewPublishCocktailsRequestWithApplicationJSONXAPIVersion10Body(server string, params *PublishCocktailsParams, body PublishCocktailsApplicationJSONXAPIVersion10RequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPublishCocktailsRequestWithBody(server, params, "application/json; x-api-version=1.0", bodyReader)
}

// NewPublishCocktailsRequestWithBody generates requests for PublishCocktails with any type of body
func NewPublishCocktailsRequestWithBody(server string, params *PublishCocktailsParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/cocktails/admin/pub")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.XKey != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "X-Key", runtime.ParamLocationHeader, *params.XKey)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-Key", headerParam0)
		}

	}

	return req, nil
}

// NewPublishIngredientsRequestWithApplicationJSONXAPIVersion10Body calls the generic PublishIngredients builder with application/json; x-api-version=1.0 body
func NewPublishIngredientsRequestWithApplicationJSONXAPIVersion10Body(server string, params *PublishIngredientsParams, body PublishIngredientsApplicationJSONXAPIVersion10RequestBody) (*http.Request, error) {
	var bodyReader io.Reader
	buf, err := json.Marshal(body)
	if err != nil {
		return nil, err
	}
	bodyReader = bytes.NewReader(buf)
	return NewPublishIngredientsRequestWithBody(server, params, "application/json; x-api-version=1.0", bodyReader)
}

// NewPublishIngredientsRequestWithBody generates requests for PublishIngredients with any type of body
func NewPublishIngredientsRequestWithBody(server string, params *PublishIngredientsParams, contentType string, body io.Reader) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/cocktails/admin/pub/ingredients")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("PUT", queryURL.String(), body)
	if err != nil {
		return nil, err
	}

	req.Header.Add("Content-Type", contentType)

	if params != nil {

		if params.XKey != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "X-Key", runtime.ParamLocationHeader, *params.XKey)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-Key", headerParam0)
		}

	}

	return req, nil
}

// NewGetCocktailCollectionsRequest generates requests for GetCocktailCollections
func NewGetCocktailCollectionsRequest(server string, params *GetCocktailCollectionsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/cocktails/collections")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.XKey != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "X-Key", runtime.ParamLocationHeader, *params.XKey)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-Key", headerParam0)
		}

	}

	return req, nil
}

// NewGetCocktailCollectionRequest generates requests for GetCocktailCollection
func NewGetCocktailCollectionRequest(server string, id string, params *GetCocktailCollectionParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/cocktails/collections/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.XKey != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "X-Key", runtime.ParamLocationHeader, *params.XKey)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-Key", headerParam0)
		}

	}

	return req, nil
}

// NewGetIngredientsRequest generates requests for GetIngredients
func NewGetIngredientsRequest(server string, params *GetIngredientsParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/cocktails/ingredients")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.Skip != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "skip", runtime.ParamLocationQuery, *params.Skip); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Take != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "take", runtime.ParamLocationQuery, *params.Take); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.Fi != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "fi", runtime.ParamLocationQuery, *params.Fi); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.XKey != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "X-Key", runtime.ParamLocationHeader, *params.XKey)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-Key", headerParam0)
		}

	}

	return req, nil
}

// NewGetCocktailIngredientFiltersRequest generates requests for GetCocktailIngredientFilters
func NewGetCocktailIngredientFiltersRequest(server string, params *GetCocktailIngredientFiltersParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/cocktails/ingredients/filters")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.XKey != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "X-Key", runtime.ParamLocationHeader, *params.XKey)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-Key", headerParam0)
		}

	}

	return req, nil
}

// NewGetIngredientRequest generates requests for GetIngredient
func NewGetIngredientRequest(server string, id string, params *GetIngredientParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/cocktails/ingredients/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.XKey != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "X-Key", runtime.ParamLocationHeader, *params.XKey)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-Key", headerParam0)
		}

	}

	return req, nil
}

// NewGetCocktailRequest generates requests for GetCocktail
func NewGetCocktailRequest(server string, id string, params *GetCocktailParams) (*http.Request, error) {
	var err error

	var pathParam0 string

	pathParam0, err = runtime.StyleParamWithLocation("simple", false, "id", runtime.ParamLocationPath, id)
	if err != nil {
		return nil, err
	}

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/cocktails/%s", pathParam0)
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	if params != nil {
		queryValues := queryURL.Query()

		if params.ResolveIngredients != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "resolveIngredients", runtime.ParamLocationQuery, *params.ResolveIngredients); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		if params.MeasurementSystem != nil {

			if queryFrag, err := runtime.StyleParamWithLocation("form", true, "measurementSystem", runtime.ParamLocationQuery, *params.MeasurementSystem); err != nil {
				return nil, err
			} else if parsed, err := url.ParseQuery(queryFrag); err != nil {
				return nil, err
			} else {
				for k, v := range parsed {
					for _, v2 := range v {
						queryValues.Add(k, v2)
					}
				}
			}

		}

		queryURL.RawQuery = queryValues.Encode()
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.XKey != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "X-Key", runtime.ParamLocationHeader, *params.XKey)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-Key", headerParam0)
		}

	}

	return req, nil
}

// NewGetPrivacyPolicyRequest generates requests for GetPrivacyPolicy
func NewGetPrivacyPolicyRequest(server string, params *GetPrivacyPolicyParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/legal/documents/privacy-policy")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.XKey != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "X-Key", runtime.ParamLocationHeader, *params.XKey)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-Key", headerParam0)
		}

	}

	return req, nil
}

// NewGetTermsOfServiceRequest generates requests for GetTermsOfService
func NewGetTermsOfServiceRequest(server string, params *GetTermsOfServiceParams) (*http.Request, error) {
	var err error

	serverURL, err := url.Parse(server)
	if err != nil {
		return nil, err
	}

	operationPath := fmt.Sprintf("/api/v1/legal/documents/terms-of-service")
	if operationPath[0] == '/' {
		operationPath = "." + operationPath
	}

	queryURL, err := serverURL.Parse(operationPath)
	if err != nil {
		return nil, err
	}

	req, err := http.NewRequest("GET", queryURL.String(), nil)
	if err != nil {
		return nil, err
	}

	if params != nil {

		if params.XKey != nil {
			var headerParam0 string

			headerParam0, err = runtime.StyleParamWithLocation("simple", false, "X-Key", runtime.ParamLocationHeader, *params.XKey)
			if err != nil {
				return nil, err
			}

			req.Header.Set("X-Key", headerParam0)
		}

	}

	return req, nil
}

func (c *Client) applyEditors(ctx context.Context, req *http.Request, additionalEditors []RequestEditorFn) error {
	for _, r := range c.RequestEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	for _, r := range additionalEditors {
		if err := r(ctx, req); err != nil {
			return err
		}
	}
	return nil
}

// ClientWithResponses builds on ClientInterface to offer response payloads
type ClientWithResponses struct {
	ClientInterface
}

// NewClientWithResponses creates a new ClientWithResponses, which wraps
// Client with return type handling
func NewClientWithResponses(server string, opts ...ClientOption) (*ClientWithResponses, error) {
	client, err := NewClient(server, opts...)
	if err != nil {
		return nil, err
	}
	return &ClientWithResponses{client}, nil
}

// WithBaseURL overrides the baseURL.
func WithBaseURL(baseURL string) ClientOption {
	return func(c *Client) error {
		newBaseURL, err := url.Parse(baseURL)
		if err != nil {
			return err
		}
		c.Server = newBaseURL.String()
		return nil
	}
}

// ClientWithResponsesInterface is the interface specification for the client with responses above.
type ClientWithResponsesInterface interface {
	// PublishCocktailsWithBodyWithResponse request with any body
	PublishCocktailsWithBodyWithResponse(ctx context.Context, params *PublishCocktailsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PublishCocktailsResponse, error)

	PublishCocktailsWithApplicationJSONXAPIVersion10BodyWithResponse(ctx context.Context, params *PublishCocktailsParams, body PublishCocktailsApplicationJSONXAPIVersion10RequestBody, reqEditors ...RequestEditorFn) (*PublishCocktailsResponse, error)

	// PublishIngredientsWithBodyWithResponse request with any body
	PublishIngredientsWithBodyWithResponse(ctx context.Context, params *PublishIngredientsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PublishIngredientsResponse, error)

	PublishIngredientsWithApplicationJSONXAPIVersion10BodyWithResponse(ctx context.Context, params *PublishIngredientsParams, body PublishIngredientsApplicationJSONXAPIVersion10RequestBody, reqEditors ...RequestEditorFn) (*PublishIngredientsResponse, error)

	// GetCocktailCollectionsWithResponse request
	GetCocktailCollectionsWithResponse(ctx context.Context, params *GetCocktailCollectionsParams, reqEditors ...RequestEditorFn) (*GetCocktailCollectionsResponse, error)

	// GetCocktailCollectionWithResponse request
	GetCocktailCollectionWithResponse(ctx context.Context, id string, params *GetCocktailCollectionParams, reqEditors ...RequestEditorFn) (*GetCocktailCollectionResponse, error)

	// GetIngredientsWithResponse request
	GetIngredientsWithResponse(ctx context.Context, params *GetIngredientsParams, reqEditors ...RequestEditorFn) (*GetIngredientsResponse, error)

	// GetCocktailIngredientFiltersWithResponse request
	GetCocktailIngredientFiltersWithResponse(ctx context.Context, params *GetCocktailIngredientFiltersParams, reqEditors ...RequestEditorFn) (*GetCocktailIngredientFiltersResponse, error)

	// GetIngredientWithResponse request
	GetIngredientWithResponse(ctx context.Context, id string, params *GetIngredientParams, reqEditors ...RequestEditorFn) (*GetIngredientResponse, error)

	// GetCocktailWithResponse request
	GetCocktailWithResponse(ctx context.Context, id string, params *GetCocktailParams, reqEditors ...RequestEditorFn) (*GetCocktailResponse, error)

	// GetPrivacyPolicyWithResponse request
	GetPrivacyPolicyWithResponse(ctx context.Context, params *GetPrivacyPolicyParams, reqEditors ...RequestEditorFn) (*GetPrivacyPolicyResponse, error)

	// GetTermsOfServiceWithResponse request
	GetTermsOfServiceWithResponse(ctx context.Context, params *GetTermsOfServiceParams, reqEditors ...RequestEditorFn) (*GetTermsOfServiceResponse, error)
}

type PublishCocktailsResponse struct {
	Body                                []byte
	HTTPResponse                        *http.Response
	ApplicationjsonXApiVersion10Default *ProblemDetails
}

// Status returns HTTPResponse.Status
func (r PublishCocktailsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PublishCocktailsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type PublishIngredientsResponse struct {
	Body                                []byte
	HTTPResponse                        *http.Response
	ApplicationjsonXApiVersion10Default *ProblemDetails
}

// Status returns HTTPResponse.Status
func (r PublishIngredientsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r PublishIngredientsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetCocktailCollectionsResponse struct {
	Body                                []byte
	HTTPResponse                        *http.Response
	ApplicationjsonXApiVersion10200     *CocktailCollectionsRs
	ApplicationjsonXApiVersion10Default *ProblemDetails
}

// Status returns HTTPResponse.Status
func (r GetCocktailCollectionsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCocktailCollectionsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetCocktailCollectionResponse struct {
	Body                                []byte
	HTTPResponse                        *http.Response
	ApplicationjsonXApiVersion10200     *CocktailCollectionRs
	ApplicationjsonXApiVersion10Default *ProblemDetails
}

// Status returns HTTPResponse.Status
func (r GetCocktailCollectionResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCocktailCollectionResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetIngredientsResponse struct {
	Body                                []byte
	HTTPResponse                        *http.Response
	ApplicationjsonXApiVersion10200     *IngredientsRs
	ApplicationjsonXApiVersion10Default *ProblemDetails
}

// Status returns HTTPResponse.Status
func (r GetIngredientsResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetIngredientsResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetCocktailIngredientFiltersResponse struct {
	Body                                []byte
	HTTPResponse                        *http.Response
	ApplicationjsonXApiVersion10200     *CocktailIngredientFiltersRs
	ApplicationjsonXApiVersion10Default *ProblemDetails
}

// Status returns HTTPResponse.Status
func (r GetCocktailIngredientFiltersResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCocktailIngredientFiltersResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetIngredientResponse struct {
	Body                                []byte
	HTTPResponse                        *http.Response
	ApplicationjsonXApiVersion10200     *IngredientRs
	ApplicationjsonXApiVersion10Default *ProblemDetails
}

// Status returns HTTPResponse.Status
func (r GetIngredientResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetIngredientResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetCocktailResponse struct {
	Body                                []byte
	HTTPResponse                        *http.Response
	ApplicationjsonXApiVersion10200     *CocktailRs
	ApplicationjsonXApiVersion10Default *ProblemDetails
}

// Status returns HTTPResponse.Status
func (r GetCocktailResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetCocktailResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetPrivacyPolicyResponse struct {
	Body                                []byte
	HTTPResponse                        *http.Response
	ApplicationjsonXApiVersion10200     *LegalDocumentRs
	ApplicationjsonXApiVersion10Default *ProblemDetails
}

// Status returns HTTPResponse.Status
func (r GetPrivacyPolicyResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetPrivacyPolicyResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

type GetTermsOfServiceResponse struct {
	Body                                []byte
	HTTPResponse                        *http.Response
	ApplicationjsonXApiVersion10200     *LegalDocumentRs
	ApplicationjsonXApiVersion10Default *ProblemDetails
}

// Status returns HTTPResponse.Status
func (r GetTermsOfServiceResponse) Status() string {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.Status
	}
	return http.StatusText(0)
}

// StatusCode returns HTTPResponse.StatusCode
func (r GetTermsOfServiceResponse) StatusCode() int {
	if r.HTTPResponse != nil {
		return r.HTTPResponse.StatusCode
	}
	return 0
}

// PublishCocktailsWithBodyWithResponse request with arbitrary body returning *PublishCocktailsResponse
func (c *ClientWithResponses) PublishCocktailsWithBodyWithResponse(ctx context.Context, params *PublishCocktailsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PublishCocktailsResponse, error) {
	rsp, err := c.PublishCocktailsWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePublishCocktailsResponse(rsp)
}

func (c *ClientWithResponses) PublishCocktailsWithApplicationJSONXAPIVersion10BodyWithResponse(ctx context.Context, params *PublishCocktailsParams, body PublishCocktailsApplicationJSONXAPIVersion10RequestBody, reqEditors ...RequestEditorFn) (*PublishCocktailsResponse, error) {
	rsp, err := c.PublishCocktailsWithApplicationJSONXAPIVersion10Body(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePublishCocktailsResponse(rsp)
}

// PublishIngredientsWithBodyWithResponse request with arbitrary body returning *PublishIngredientsResponse
func (c *ClientWithResponses) PublishIngredientsWithBodyWithResponse(ctx context.Context, params *PublishIngredientsParams, contentType string, body io.Reader, reqEditors ...RequestEditorFn) (*PublishIngredientsResponse, error) {
	rsp, err := c.PublishIngredientsWithBody(ctx, params, contentType, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePublishIngredientsResponse(rsp)
}

func (c *ClientWithResponses) PublishIngredientsWithApplicationJSONXAPIVersion10BodyWithResponse(ctx context.Context, params *PublishIngredientsParams, body PublishIngredientsApplicationJSONXAPIVersion10RequestBody, reqEditors ...RequestEditorFn) (*PublishIngredientsResponse, error) {
	rsp, err := c.PublishIngredientsWithApplicationJSONXAPIVersion10Body(ctx, params, body, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParsePublishIngredientsResponse(rsp)
}

// GetCocktailCollectionsWithResponse request returning *GetCocktailCollectionsResponse
func (c *ClientWithResponses) GetCocktailCollectionsWithResponse(ctx context.Context, params *GetCocktailCollectionsParams, reqEditors ...RequestEditorFn) (*GetCocktailCollectionsResponse, error) {
	rsp, err := c.GetCocktailCollections(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCocktailCollectionsResponse(rsp)
}

// GetCocktailCollectionWithResponse request returning *GetCocktailCollectionResponse
func (c *ClientWithResponses) GetCocktailCollectionWithResponse(ctx context.Context, id string, params *GetCocktailCollectionParams, reqEditors ...RequestEditorFn) (*GetCocktailCollectionResponse, error) {
	rsp, err := c.GetCocktailCollection(ctx, id, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCocktailCollectionResponse(rsp)
}

// GetIngredientsWithResponse request returning *GetIngredientsResponse
func (c *ClientWithResponses) GetIngredientsWithResponse(ctx context.Context, params *GetIngredientsParams, reqEditors ...RequestEditorFn) (*GetIngredientsResponse, error) {
	rsp, err := c.GetIngredients(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetIngredientsResponse(rsp)
}

// GetCocktailIngredientFiltersWithResponse request returning *GetCocktailIngredientFiltersResponse
func (c *ClientWithResponses) GetCocktailIngredientFiltersWithResponse(ctx context.Context, params *GetCocktailIngredientFiltersParams, reqEditors ...RequestEditorFn) (*GetCocktailIngredientFiltersResponse, error) {
	rsp, err := c.GetCocktailIngredientFilters(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCocktailIngredientFiltersResponse(rsp)
}

// GetIngredientWithResponse request returning *GetIngredientResponse
func (c *ClientWithResponses) GetIngredientWithResponse(ctx context.Context, id string, params *GetIngredientParams, reqEditors ...RequestEditorFn) (*GetIngredientResponse, error) {
	rsp, err := c.GetIngredient(ctx, id, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetIngredientResponse(rsp)
}

// GetCocktailWithResponse request returning *GetCocktailResponse
func (c *ClientWithResponses) GetCocktailWithResponse(ctx context.Context, id string, params *GetCocktailParams, reqEditors ...RequestEditorFn) (*GetCocktailResponse, error) {
	rsp, err := c.GetCocktail(ctx, id, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetCocktailResponse(rsp)
}

// GetPrivacyPolicyWithResponse request returning *GetPrivacyPolicyResponse
func (c *ClientWithResponses) GetPrivacyPolicyWithResponse(ctx context.Context, params *GetPrivacyPolicyParams, reqEditors ...RequestEditorFn) (*GetPrivacyPolicyResponse, error) {
	rsp, err := c.GetPrivacyPolicy(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetPrivacyPolicyResponse(rsp)
}

// GetTermsOfServiceWithResponse request returning *GetTermsOfServiceResponse
func (c *ClientWithResponses) GetTermsOfServiceWithResponse(ctx context.Context, params *GetTermsOfServiceParams, reqEditors ...RequestEditorFn) (*GetTermsOfServiceResponse, error) {
	rsp, err := c.GetTermsOfService(ctx, params, reqEditors...)
	if err != nil {
		return nil, err
	}
	return ParseGetTermsOfServiceResponse(rsp)
}

// ParsePublishCocktailsResponse parses an HTTP response from a PublishCocktailsWithResponse call
func ParsePublishCocktailsResponse(rsp *http.Response) (*PublishCocktailsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PublishCocktailsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ProblemDetails
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationjsonXApiVersion10Default = &dest

	}

	return response, nil
}

// ParsePublishIngredientsResponse parses an HTTP response from a PublishIngredientsWithResponse call
func ParsePublishIngredientsResponse(rsp *http.Response) (*PublishIngredientsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &PublishIngredientsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ProblemDetails
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationjsonXApiVersion10Default = &dest

	}

	return response, nil
}

// ParseGetCocktailCollectionsResponse parses an HTTP response from a GetCocktailCollectionsWithResponse call
func ParseGetCocktailCollectionsResponse(rsp *http.Response) (*GetCocktailCollectionsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCocktailCollectionsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CocktailCollectionsRs
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationjsonXApiVersion10200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ProblemDetails
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationjsonXApiVersion10Default = &dest

	}

	return response, nil
}

// ParseGetCocktailCollectionResponse parses an HTTP response from a GetCocktailCollectionWithResponse call
func ParseGetCocktailCollectionResponse(rsp *http.Response) (*GetCocktailCollectionResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCocktailCollectionResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CocktailCollectionRs
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationjsonXApiVersion10200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ProblemDetails
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationjsonXApiVersion10Default = &dest

	}

	return response, nil
}

// ParseGetIngredientsResponse parses an HTTP response from a GetIngredientsWithResponse call
func ParseGetIngredientsResponse(rsp *http.Response) (*GetIngredientsResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetIngredientsResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest IngredientsRs
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationjsonXApiVersion10200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ProblemDetails
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationjsonXApiVersion10Default = &dest

	}

	return response, nil
}

// ParseGetCocktailIngredientFiltersResponse parses an HTTP response from a GetCocktailIngredientFiltersWithResponse call
func ParseGetCocktailIngredientFiltersResponse(rsp *http.Response) (*GetCocktailIngredientFiltersResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCocktailIngredientFiltersResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CocktailIngredientFiltersRs
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationjsonXApiVersion10200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ProblemDetails
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationjsonXApiVersion10Default = &dest

	}

	return response, nil
}

// ParseGetIngredientResponse parses an HTTP response from a GetIngredientWithResponse call
func ParseGetIngredientResponse(rsp *http.Response) (*GetIngredientResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetIngredientResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest IngredientRs
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationjsonXApiVersion10200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ProblemDetails
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationjsonXApiVersion10Default = &dest

	}

	return response, nil
}

// ParseGetCocktailResponse parses an HTTP response from a GetCocktailWithResponse call
func ParseGetCocktailResponse(rsp *http.Response) (*GetCocktailResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetCocktailResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest CocktailRs
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationjsonXApiVersion10200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ProblemDetails
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationjsonXApiVersion10Default = &dest

	}

	return response, nil
}

// ParseGetPrivacyPolicyResponse parses an HTTP response from a GetPrivacyPolicyWithResponse call
func ParseGetPrivacyPolicyResponse(rsp *http.Response) (*GetPrivacyPolicyResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetPrivacyPolicyResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest LegalDocumentRs
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationjsonXApiVersion10200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ProblemDetails
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationjsonXApiVersion10Default = &dest

	}

	return response, nil
}

// ParseGetTermsOfServiceResponse parses an HTTP response from a GetTermsOfServiceWithResponse call
func ParseGetTermsOfServiceResponse(rsp *http.Response) (*GetTermsOfServiceResponse, error) {
	bodyBytes, err := io.ReadAll(rsp.Body)
	defer func() { _ = rsp.Body.Close() }()
	if err != nil {
		return nil, err
	}

	response := &GetTermsOfServiceResponse{
		Body:         bodyBytes,
		HTTPResponse: rsp,
	}

	switch {
	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && rsp.StatusCode == 200:
		var dest LegalDocumentRs
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationjsonXApiVersion10200 = &dest

	case strings.Contains(rsp.Header.Get("Content-Type"), "json") && true:
		var dest ProblemDetails
		if err := json.Unmarshal(bodyBytes, &dest); err != nil {
			return nil, err
		}
		response.ApplicationjsonXApiVersion10Default = &dest

	}

	return response, nil
}
