
// ------------------------------------------------------------
// Get Healthz
// ------------------------------------------------------------

GET {{host}}/healthz
Accept: application/json

###

// ------------------------------------------------------------
// Get Version
// ------------------------------------------------------------

GET {{host}}/version
Accept: application/json

###

// ------------------------------------------------------------
// POST Convert to Plain Text
// ------------------------------------------------------------

POST {{host}}/mcp
Accept: application/json
Content-Type: application/json
Mcp-Session-Id: mcp-session-a94254f7-0378-45d1-822f-efcea775a5a8

{
  "jsonrpc": "2.0",
  "id": "1",
  "method": "tools/call",
  "params": {
    "name": "convert_to_plaintext",
    "arguments": {
      "content": "## This is my markdown: **bold** *italic* `code` [link](https://example.com).  It also has emojis: 😄🍹. And HTML tags: <b>bold</b> <i>italic</i>. And some weird JSON characters: \\u2028\\u2029"
    }
  }
}

###
